spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:spring-cp2-2tdspm-brindes}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME:XXX}
    password: ${DB_DESENV_PASSWORD:XXX}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true